FROM python:3.10-slim

WORKDIR /ui

COPY ui/streamlit_app.py ./streamlit_app.py
COPY requirements.txt ../requirements.txt
RUN pip install --no-cache-dir -r ../requirements.txt

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
