services:

  mongo:
    image: mongo:6
    container_name: mongo_rag
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ragdb
      MONGO_INITDB_ROOT_USERNAME: raguser
      MONGO_INITDB_ROOT_PASSWORD: ragpass
    networks:
      - rag-net

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   restart: always
  #   ports:
  #     - "11434:11434"  # Port par défaut d’Ollama
  #   volumes:
  #     - ./ollama_data:/root/.ollama  # Pour persister les modèles téléchargés
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: >
  #     "ollama serve & 
  #     sleep 5 && 
  #     ollama pull mistral && 
  #     wait"
  #   networks:
  #     - rag-net

  rag-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: rag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    # environment:
      # - OLLAMA_BASE_URL=http://ollama:11434  # URL du service Ollama depuis l'API
    depends_on:
      # - ollama
      - mongo
    networks:
      - rag-net

  rag-ui:
    build:
      context: .
      dockerfile: ui/dockerfile
    container_name: rag-ui
    ports:
      - "8501:8501"
    depends_on:
      - rag-api
    environment:
      - API_URL=http://rag-api:8000/ask
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge

# volumes:
#   ollama_data:
