FROM qdrant/qdrant

WORKDIR /home

COPY qdrant_rag/scripts .
COPY requirements.txt .
RUN apt install install python-is-python3 -y
RUN apt install python-is-python3-pip -y
RUN pip install --no-cache -r ./requirements.txt

CMD [ "python3","vectorize.py" ]
 